spring.application.name=database2
spring.datasource.url=jdbc:postgresql://localhost:5432/produtosDB
spring.datasource.username=postgres
spring.datasource.password=LpostCas02
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true